pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                echo "Repository cloned successfully"
            }
        }

        stage('Build') {
            steps {
                sh 'echo Building from custom Jenkinsfile path'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Testing successful'
            }
        }
    }
}
